# 基础训练配置
output_dir: ${hydra:run.dir}/outputs
num_train_epochs: 3
learning_rate: 5e-5
weight_decay: 0.01
warmup_ratio: 0.1

optimizer_type: adamw
scheduler_type: linear

gradient_accumulation_steps: 1
max_grad_norm: 1.0

eval_steps: 500
save_steps: 500
save_total_limit: 3
logging_steps: 100

early_stopping_patience: 3
early_stopping_threshold: 0.001

seed: 42
